# ======================================================================================
# RESUMEN
# ======================================================================================
# Este archivo centraliza toda la configuración del entorno. Evita tener credenciales
# o direcciones IP dispersas por el código Java.
#
# SECCIONES CLAVE:
# 1. BASE DE DATOS: Conexión JDBC a MySQL.
# 2. JPA/HIBERNATE: Configuración de cómo Java gestiona las tablas (creación automática).
# 3. SPOTIFY API: Credenciales (Client ID/Secret) para OAuth 2.0.
# 4. EMAIL: Configuración del servidor SMTP (Mailtrap para pruebas seguras).
# ======================================================================================

spring.application.name=backend

# --- 1. CONEXIÓN BASE DE DATOS (MySQL) ---
# URL de conexión JDBC. 'useSSL=false' para desarrollo local.
spring.datasource.url=jdbc:mysql://localhost:3306/gramola_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# --- 2. JPA / HIBERNATE (El motor de BD) ---
# 'update': Si cambio una clase Java, Hibernate actualiza la tabla automáticamente sin borrar datos.
spring.jpa.hibernate.ddl-auto=update
# 'show-sql=true': Muestra las queries en la consola (útil para depurar).
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# URL de retorno donde Spotify manda el código tras el login (apunta a nuestro Controller).
spotify.redirect.uri=http://127.0.0.1:4200/callback

# --- 4. SERVIDOR DE CORREO (Mailtrap) ---
# Usamos Mailtrap para simular envíos de email sin spamear cuentas reales.
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b85637c16644c0
spring.mail.password=a2aee8ff7f3d22

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.key.secret=sk_test_51Sn1eQRvZ6y98AypUhW8H7GU5Znv0WQR91zZn0aOKsDFN0xbsBixWSWvmgK3pxqcLoYfyZUi0G8i8CeuIzpPLbBf00DHzQWIeC